version: '3'
services:
  redmine:
    image: inspiredgeek/redmine-alpine:latest
    ports:
      - "3000:3000"
    environment:
      DB_ADAPTER: mysql2
      DB_HOST: db
      DB_PASSWORD: redmine
      DB_USER: redmine
      DB_NAME: redmine
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
