version: '2'
services:
    redmine:
        image: inspiredgeek/redmine-alpine:latest
        ports:
            - "3000:3000"
        environment:
            REDMINE_DB_MYSQL: db
            REDMINE_DB_PASSWORD: redmine
            REDMINE_DB_USERNAME: redmine
            REDMINE_DB_DATABASE: redmine
        depends_on:
            - db
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: redmine
            MYSQL_DATABASE: redmine
            MYSQL_USER: redmine
            MYSQL_PASSWORD: redmine
