version: '3'
services:
  redmine:
    image: inspiredgeek/redmine-alpine:unicorn
    ports:
      - "8080:8080"
    environment:
      DB_ADAPTER: mysql2
      DB_HOST: db
      DB_PASSWORD: redmine
      DB_USER: redmine
      DB_NAME: redmine
    volumes:
      - redmine-files:/usr/src/redmine/files
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    volumes:
      - redmine-data:/var/lib/mysql
volumes:
  redmine-files:
  redmine-data:
