name: Build Image using Containerfile
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: redmine-alpine
          tags: ${{ github.ref_name }}
          containerfiles: |
            ./Containerfile
